//MooTools, My Object Oriented Javascript Tools. Copyright (c) 2006-2007 Valerio Proietti, <http://mad4milk.net>, MIT Style License.

var MooTools={"version":"1.2dev","build":"1.2b2"};var Native=function(J){J=J||{};var F=J.afterImplement||function(){};var G=J.generics;G=(G!==false);
var H=J.legacy;var E=J.initialize;var B=J.protect;var A=J.name;var C=E||H;C.constructor=Native;C.$family={name:"native"};if(H&&E){C.prototype=H.prototype;
}C.prototype.constructor=C;if(A){var D=A.toLowerCase();C.prototype.$family={name:D};Native.typize(C,D);}var I=function(M,K,N,L){if(!B||L||!M.prototype[K]){M.prototype[K]=N;
}if(G){Native.genericize(M,K,B);}F.call(M,K,N);return M;};C.implement=function(L,K,N){if(typeof L=="string"){return I(this,L,K,N);}for(var M in L){I(this,M,L[M],K);
}return this;};C.alias=function(K,M,L){K=this.prototype[K];if(K){I(this,M,K,L);}return this;};return C;};Native.implement=function(D,C){for(var B=0,A=D.length;
B<A;B++){D[B].implement(C);}};Native.genericize=function(B,C,A){if((!A||!B[C])&&typeof B.prototype[C]=="function"){B[C]=function(){var D=Array.prototype.slice.call(arguments);
return B.prototype[C].apply(D.shift(),D);};}};Native.typize=function(A,B){if(!A.type){A.type=function(C){return($type(C)===B);};}};(function(B){for(var A in B){Native.typize(B[A],A.toLowerCase());
}})({"Boolean":Boolean,"Native":Native,"Object":Object});(function(B){for(var A in B){new Native({name:A,initialize:B[A],protect:true});}})({"String":String,"Function":Function,"Number":Number,"Array":Array,"RegExp":RegExp,"Date":Date});
(function(C,B){for(var D=0,A=B.length;D<A;D++){Native.genericize(C,B[D],true);}return arguments.callee;})(Array,["pop","push","reverse","shift","sort","splice","unshift","concat","join","slice","toString","valueOf","indexOf","lastIndexOf"])(String,["charAt","charCodeAt","concat","indexOf","lastIndexOf","match","replace","search","slice","split","substr","substring","toLowerCase","toUpperCase","valueOf"]);
function $chk(A){return !!(A||A===0);}function $clear(A){clearTimeout(A);clearInterval(A);return null;}function $defined(A){return(A!=undefined);}function $empty(){}function $arguments(A){return function(){return arguments[A];
};}function $lambda(A){return(typeof A=="function")?A:function(){return A;};}function $extend(C,A){for(var B in (A||{})){C[B]=A[B];}return C;}function $unlink(C){var B=null;
switch($type(C)){case"object":B={};for(var E in C){B[E]=$unlink(C[E]);}break;case"array":B=[];for(var D=0,A=C.length;D<A;D++){B[D]=$unlink(C[D]);}break;
default:return C;}return B;}function $merge(){var E={};for(var D=0,A=arguments.length;D<A;D++){var B=arguments[D];if($type(B)!="object"){continue;}for(var C in B){var G=B[C],F=E[C];
E[C]=(F&&$type(G)=="object"&&$type(F)=="object")?$merge(F,G):$unlink(G);}}return E;}function $pick(){for(var B=0,A=arguments.length;B<A;B++){if($defined(arguments[B])){return arguments[B];
}}return null;}function $random(B,A){return Math.floor(Math.random()*(A-B+1)+B);}function $splat(B){var A=$type(B);return(A)?((A!="array"&&A!="arguments")?[B]:B):[];
}var $time=Date.now||function(){return new Date().getTime();};function $try(B,D,A){try{return B.apply(D,$splat(A));}catch(C){return false;}}function $type(A){if(A==undefined){return false;
}if(A.$family){return(A.$family.name=="number"&&!isFinite(A))?false:A.$family.name;}if(A.nodeName){switch(A.nodeType){case 1:return"element";case 3:return(/\S/).test(A.nodeValue)?"textnode":"whitespace";
}}else{if(typeof A.length=="number"){if(A.callee){return"arguments";}else{if(A.item){return"collection";}}}}return typeof A;}var Hash=new Native({name:"Hash",initialize:function(A){if($type(A)=="hash"){A=$unlink(A.getClean());
}for(var B in A){if(!this[B]){this[B]=A[B];}}return this;}});Hash.implement({getLength:function(){var B=0;for(var A in this){if(this.hasOwnProperty(A)){B++;
}}return B;},forEach:function(B,C){for(var A in this){if(this.hasOwnProperty(A)){B.call(C,this[A],A,this);}}},getClean:function(){var B={};for(var A in this){if(this.hasOwnProperty(A)){B[A]=this[A];
}}return B;}});Hash.alias("forEach","each");function $H(A){return new Hash(A);}Array.implement({forEach:function(C,D){for(var B=0,A=this.length;B<A;B++){C.call(D,this[B],B,this);
}}});Array.alias("forEach","each");function $A(C){if($type(C)=="collection"){var D=[];for(var B=0,A=C.length;B<A;B++){D[B]=C[B];}return D;}return Array.prototype.slice.call(C);
}function $each(C,B,D){var A=$type(C);((A=="arguments"||A=="collection"||A=="array")?Array:Hash).each(C,B,D);}var Browser=new Hash({Engine:{name:"unknown",version:""},Platform:{name:(navigator.platform.match(/mac|win|linux|nix/i)||["other"])[0].toLowerCase()},Features:{xhr:!!(window.XMLHttpRequest),xpath:!!(document.evaluate),air:!!(window.runtime)}});
if(window.opera){Browser.Engine.name="presto";}else{if(window.ActiveXObject){Browser.Engine={name:"trident",version:(Browser.Features.xhr)?5:4};}else{if(!navigator.taintEnabled){Browser.Engine={name:"webkit",version:(Browser.Features.xpath)?420:419};
}else{if(document.getBoxObjectFor!=null){Browser.Engine.name="gecko";}}}}Browser.Engine[Browser.Engine.name]=Browser.Engine[Browser.Engine.name+Browser.Engine.version]=true;
Browser.Platform[Browser.Platform.name]=true;function $exec(B){if(!B){return B;}if(window.execScript){window.execScript(B);}else{var A=document.createElement("script");
A.setAttribute("type","text/javascript");A.text=B;document.head.appendChild(A);document.head.removeChild(A);}return B;}Native.UID=0;var Window=new Native({name:"Window",legacy:window.Window,initialize:function(A){if(!A.Element){A.Element=$empty;
if(Browser.Engine.webkit){A.document.createElement("iframe");}A.Element.prototype=(Browser.Engine.webkit)?window["[[DOMElement.prototype]]"]:{};}A.uid=Native.UID++;
return $extend(A,Window.Prototype);},afterImplement:function(B,A){window[B]=Window.Prototype[B]=A;}});Window.Prototype={$family:{name:"window"}};new Window(window);
var Document=new Native({name:"Document",legacy:window.Document,initialize:function(A){A.head=A.getElementsByTagName("head")[0];A.html=A.getElementsByTagName("html")[0];
A.window=A.defaultView||A.parentWindow;if(Browser.Engine.trident4){$try(function(){A.execCommand("BackgroundImageCache",false,true);});}A.uid=Native.UID++;
return $extend(A,Document.Prototype);},afterImplement:function(B,A){document[B]=Document.Prototype[B]=A;}});Document.Prototype={$family:{name:"document"}};
new Document(document);Array.implement({every:function(C,D){for(var B=0,A=this.length;B<A;B++){if(!C.call(D,this[B],B,this)){return false;}}return true;
},filter:function(D,E){var C=[];for(var B=0,A=this.length;B<A;B++){if(D.call(E,this[B],B,this)){C.push(this[B]);}}return C;},clean:function(){return this.filter($arguments(0));
},indexOf:function(C,D){var A=this.length;for(var B=(D<0)?Math.max(0,A+D):D||0;B<A;B++){if(this[B]===C){return B;}}return -1;},map:function(D,E){var C=[];
for(var B=0,A=this.length;B<A;B++){C[B]=D.call(E,this[B],B,this);}return C;},some:function(C,D){for(var B=0,A=this.length;B<A;B++){if(C.call(D,this[B],B,this)){return true;
}}return false;},associate:function(C){var D={},B=Math.min(this.length,C.length);for(var A=0;A<B;A++){D[C[A]]=this[A];}return D;},link:function(C){var A={};
for(var E=0,B=this.length;E<B;E++){for(var D in C){if(C[D](this[E])){A[D]=this[E];delete C[D];break;}}}return A;},contains:function(A,B){return this.indexOf(A,B)!=-1;
},extend:function(C){for(var B=0,A=C.length;B<A;B++){this.push(C[B]);}return this;},getLast:function(){return(this.length)?this[this.length-1]:null;},getRandom:function(){return(this.length)?this[$random(0,this.length-1)]:null;
},include:function(A){if(!this.contains(A)){this.push(A);}return this;},merge:function(C){for(var B=0,A=C.length;B<A;B++){this.include(C[B]);}return this;
},remove:function(B){for(var A=this.length;A--;A){if(this[A]===B){this.splice(A,1);}}return this;},empty:function(){this.length=0;return this;},flatten:function(){var D=[];
for(var B=0,A=this.length;B<A;B++){var C=$type(this[B]);if(!C){continue;}D=D.concat((C=="array"||C=="collection"||C=="arguments")?Array.flatten(this[B]):this[B]);
}return D;},hexToRgb:function(B){if(this.length!=3){return null;}var A=this.map(function(C){if(C.length==1){C+=C;}return C.toInt(16);});return(B)?A:"rgb("+A+")";
},rgbToHex:function(D){if(this.length<3){return null;}if(this.length==4&&this[3]==0&&!D){return"transparent";}var B=[];for(var A=0;A<3;A++){var C=(this[A]-0).toString(16);
B.push((C.length==1)?"0"+C:C);}return(D)?B:"#"+B.join("");}});Function.implement({extend:function(A){for(var B in A){this[B]=A[B];}return this;},create:function(B){var A=this;
B=B||{};return function(D){var C=B.arguments;C=$defined(C)?$splat(C):Array.slice(arguments,(B.event)?1:0);if(B.event){C=[D||window.event].extend(C);}var E=function(){return A.apply(B.bind||null,C);
};if(B.delay){return setTimeout(E,B.delay);}if(B.periodical){return setInterval(E,B.periodical);}if(B.attempt){return $try(E);}return E();};},pass:function(A,B){return this.create({"arguments":A,"bind":B});
},attempt:function(A,B){return this.create({"arguments":A,"bind":B,"attempt":true})();},bind:function(B,A){return this.create({"bind":B,"arguments":A});
},bindWithEvent:function(B,A){return this.create({"bind":B,"event":true,"arguments":A});},delay:function(B,C,A){return this.create({"delay":B,"bind":C,"arguments":A})();
},periodical:function(A,C,B){return this.create({"periodical":A,"bind":C,"arguments":B})();},run:function(A,B){return this.apply(B,$splat(A));}});Number.implement({limit:function(B,A){return Math.min(A,Math.max(B,this));
},round:function(A){A=Math.pow(10,A||0);return Math.round(this*A)/A;},times:function(B,C){for(var A=0;A<this;A++){B.call(C,A,this);}},toFloat:function(){return parseFloat(this);
},toInt:function(A){return parseInt(this,A||10);}});Number.alias("times","each");(function(B){var A={};B.each(function(C){if(!Number[C]){A[C]=function(){return Math[C].apply(null,[this].concat($A(arguments)));
};}});Number.implement(A);})(["abs","acos","asin","atan","atan2","ceil","cos","exp","floor","log","max","min","pow","sin","sqrt","tan"]);String.implement({test:function(A,B){return((typeof A=="string")?new RegExp(A,B):A).test(this);
},contains:function(A,B){return(B)?(B+this+B).indexOf(B+A+B)>-1:this.indexOf(A)>-1;},trim:function(){return this.replace(/^\s+|\s+$/g,"");},clean:function(){return this.replace(/\s+/g," ").trim();
},camelCase:function(){return this.replace(/-\D/g,function(A){return A.charAt(1).toUpperCase();});},hyphenate:function(){return this.replace(/[A-Z]/g,function(A){return("-"+A.charAt(0).toLowerCase());
});},capitalize:function(){return this.replace(/\b[a-z]/g,function(A){return A.toUpperCase();});},escapeRegExp:function(){return this.replace(/([-.*+?^${}()|[\]\/\\])/g,"\\$1");
},toInt:function(A){return parseInt(this,A||10);},toFloat:function(){return parseFloat(this);},hexToRgb:function(B){var A=this.match(/^#?(\w{1,2})(\w{1,2})(\w{1,2})$/);
return(A)?A.slice(1).hexToRgb(B):null;},rgbToHex:function(B){var A=this.match(/\d{1,3}/g);return(A)?A.rgbToHex(B):null;},stripScripts:function(B){var A="";
var C=this.replace(/<script[^>]*>([\s\S]*?)<\/script>/gi,function(){A+=arguments[1]+"\n";return"";});if(B===true){$exec(A);}else{if($type(B)=="function"){B(A,C);
}}return C;}});Hash.implement({has:Object.prototype.hasOwnProperty,keyOf:function(B){for(var A in this){if(this.hasOwnProperty(A)&&this[A]===B){return A;
}}return null;},hasValue:function(A){return(Hash.keyOf(this,A)!==null);},extend:function(A){Hash.each(A,function(C,B){Hash.set(this,B,C);},this);return this;
},merge:function(A){Hash.each(A,function(C,B){Hash.include(this,B,C);},this);return this;},remove:function(A){if(this.hasOwnProperty(A)){delete this[A];
}return this;},get:function(A){return(this.hasOwnProperty(A))?this[A]:null;},set:function(A,B){if(!this[A]||this.hasOwnProperty(A)){this[A]=B;}return this;
},empty:function(){Hash.each(this,function(B,A){delete this[A];},this);return this;},include:function(B,C){var A=this[B];if(!$defined(A)){this[B]=C;}return this;
},map:function(B,C){var A=new Hash;Hash.each(this,function(E,D){A.set(D,B.call(C,E,D,this));},this);return A;},filter:function(B,C){var A=new Hash;Hash.each(this,function(E,D){if(B.call(C,E,D,this)){A.set(D,E);
}},this);return A;},every:function(B,C){for(var A in this){if(this.hasOwnProperty(A)&&!B.call(C,this[A],A)){return false;}}return true;},some:function(B,C){for(var A in this){if(this.hasOwnProperty(A)&&B.call(C,this[A],A)){return true;
}}return false;},getKeys:function(){var A=[];Hash.each(this,function(C,B){A.push(B);});return A;},getValues:function(){var A=[];Hash.each(this,function(B){A.push(B);
});return A;},toQueryString:function(){var A=[];Hash.each(this,function(C,B){$splat(C).each(function(D){A.push(B+"="+encodeURIComponent(D));});});return A.join("&");
}});Hash.alias("keyOf","indexOf").alias("hasValue","contains").alias("remove","erase");var Event=new Native({name:"Event",initialize:function(A,F){F=F||window;
A=A||F.event;if(A.$extended){return A;}this.$extended=true;var J=A.type;var G=A.target||A.srcElement;while(G&&G.nodeType==3){G=G.parentNode;}if(J.match(/DOMMouseScroll|mousewheel/)){var I=(A.wheelDelta)?A.wheelDelta/120:-(A.detail||0)/3;
}else{if(J.test(/key/)){var B=A.which||A.keyCode;var L=Event.Keys.keyOf(B);if(J=="keydown"){var D=B-111;if(D>0&&D<13){L="f"+D;}}L=L||String.fromCharCode(B).toLowerCase();
}else{if(J.match(/(click|mouse|menu)/i)){var H={x:A.pageX||A.clientX+F.document.documentElement.scrollLeft,y:A.pageY||A.clientY+F.document.documentElement.scrollTop};
var C={x:A.pageX?A.pageX-F.pageXOffset:A.clientX,y:A.pageY?A.pageY-F.pageYOffset:A.clientY};var E=(A.which==3)||(A.button==2);var K=null;if(J.match(/over|out/)){switch(J){case"mouseover":K=A.relatedTarget||A.fromElement;
break;case"mouseout":K=A.relatedTarget||A.toElement;}if((function(){while(K&&K.nodeType==3){K=K.parentNode;}}).create({attempt:Browser.Engine.gecko})()===false){K=false;
}}}}}return $extend(this,{event:A,type:J,page:H,client:C,rightClick:E,wheel:I,relatedTarget:K,target:G,code:B,key:L,shift:A.shiftKey,control:A.ctrlKey,alt:A.altKey,meta:A.metaKey});
}});Event.Keys=new Hash({"enter":13,"up":38,"down":40,"left":37,"right":39,"esc":27,"space":32,"backspace":8,"tab":9,"delete":46});Event.implement({stop:function(){return this.stopPropagation().preventDefault();
},stopPropagation:function(){if(this.event.stopPropagation){this.event.stopPropagation();}else{this.event.cancelBubble=true;}return this;},preventDefault:function(){if(this.event.preventDefault){this.event.preventDefault();
}else{this.event.returnValue=false;}return this;}});var Class=new Native({name:"Class",initialize:function(B){B=B||{};var A=function(){for(var D in this){this[D]=$unlink(this[D]);
}this.parent=null;["Implements","Extends"].each(function(E){if(!this[E]){return ;}Class[E](this,this[E]);delete this[E];},this);this.constructor=A;var C=(arguments[0]!==$empty&&this.initialize)?this.initialize.apply(this,arguments):this;
if(this.options&&this.options.initialize){this.options.initialize.call(this);}return C;};$extend(A,this);A.constructor=Class;A.prototype=B;return A;}});
Class.implement({implement:function(){Class.Implements(this.prototype,Array.slice(arguments));return this;}});Class.Implements=function(A,B){$splat(B).each(function(C){$extend(A,($type(C)=="class")?new C($empty):C);
});};Class.Extends=function(C,A){A=new A($empty);for(var E in A){var B=A[E];var D=C[E];C[E]=(function(G,H){if($defined(H)&&G!=H){var F=$type(H);if(F!=$type(G)){return H;
}switch(F){case"function":return function(){H.parent=C.parent=G.bind(this);var I=H.apply(this,arguments);C.parent=H.parent;return I;};case"object":return $merge(G,H);
default:return H;}}return G;})(B,D);}};Class.prototype.extend=function(A){A.Extends=this;return new Class(A);};var Chain=new Class({chain:function(){this.$chain=(this.$chain||[]).extend(arguments);
return this;},callChain:function(){if(this.$chain&&this.$chain.length){this.$chain.shift().apply(this,arguments);}return this;},clearChain:function(){if(this.$chain){this.$chain.empty();
}return this;}});var Events=new Class({addEvent:function(C,B,A){if(B!=$empty){this.$events=this.$events||{};this.$events[C]=this.$events[C]||[];this.$events[C].include(B);
if(A){B.internal=true;}}return this;},addEvents:function(A){for(var B in A){this.addEvent(B,A[B]);}return this;},fireEvent:function(C,B,A){if(!this.$events||!this.$events[C]){return this;
}this.$events[C].each(function(D){D.create({"bind":this,"delay":A,"arguments":B})();},this);return this;},removeEvent:function(B,A){if(!this.$events||!this.$events[B]){return this;
}if(!A.internal){this.$events[B].remove(A);}return this;},removeEvents:function(C){for(var D in this.$events){if(C&&C!=D){continue;}var B=this.$events[D];
for(var A=B.length;A--;A){this.removeEvent(D,B[A]);}}return this;}});var Options=new Class({setOptions:function(){this.options=$merge.run([this.options].extend(arguments));
if(!this.addEvent){return this;}for(var A in this.options){if($type(this.options[A])!="function"||!(/^on[A-Z]/).test(A)){continue;}this.addEvent(A,this.options[A]);
delete this.options[A];}return this;}});Document.implement({newElement:function(A,B){if(Browser.Engine.trident&&B){["name","type","checked"].each(function(C){if(!B[C]){return ;
}A+=" "+C+'="'+B[C]+'"';if(C!="checked"){delete B[C];}});A="<"+A+">";}return $.element(this.createElement(A)).set(B);},newTextNode:function(A){return this.createTextNode(A);
},getDocument:function(){return this;},getWindow:function(){return this.defaultView||this.parentWindow;}});var Element=new Native({name:"Element",legacy:window.Element,initialize:function(A,B){var C=Element.Constructors.get(A);
if(C){return C(B);}if(typeof A=="string"){return document.newElement(A,B);}return $(A).set(B);},afterImplement:function(A,B){if(!Array[A]){Elements.implement(A,Elements.multi(A));
}Element.Prototype[A]=B;}});Element.Prototype={$family:{name:"element"}};Element.Constructors=new Hash;var IFrame=new Native({name:"IFrame",generics:false,initialize:function(){Native.UID++;
var E=Array.link(arguments,{properties:Object.type,iframe:$defined});var C=E.properties||{};var B=$(E.iframe)||false;var D=C.onload||$empty;delete C.onload;
C.id=C.name=$pick(C.id,C.name,B.id,B.name,"IFrame_"+Native.UID);((B=B||new Element("iframe"))).set(C);var A=function(){var F=$try(function(){return B.contentWindow.location.host;
});if(F&&F==window.location.host){B.window=B.contentWindow;var H=new Window(B.window);var G=new Document(B.window.document);$extend(H.Element.prototype,Element.Prototype);
}D.call(B.contentWindow);};(!window.frames[C.id])?B.addListener("load",A):A();return B;}});var Elements=new Native({initialize:function(F,B){B=$extend({ddup:true,cash:true},B);
F=F||[];if(B.ddup||B.cash){var G={};var E=[];for(var C=0,A=F.length;C<A;C++){var D=$.element(F[C],!B.cash);if(B.ddup){if(G[D.uid]){continue;}G[D.uid]=true;
}E.push(D);}F=E;}return(B.cash)?$extend(F,this):F;}});Elements.implement({filterBy:function(A){if(!A){return this;}return new Elements(this.filter((typeof A=="string")?function(B){return B.match(A);
}:A));}});Elements.multi=function(A){return function(){var B=[];var F=true;for(var D=0,C=this.length;D<C;D++){var E=this[D][A].apply(this[D],arguments);
B.push(E);if(F){F=($type(E)=="element");}}return(F)?new Elements(B):B;};};Window.implement({$:function(B,C){if(B&&B.$attributes){return B;}var A=$type(B);
return($[A])?$[A](B,C,this.document):null;},$$:function(A){if(arguments.length==1&&typeof A=="string"){return this.document.getElements(A);}var F=[];var C=Array.flatten(arguments);
for(var D=0,B=C.length;D<B;D++){var E=C[D];switch($type(E)){case"element":E=[E];break;case"string":E=this.document.getElements(E,true);break;default:E=false;
}if(E){F.extend(E);}}return new Elements(F);},getDocument:function(){return this.document;},getWindow:function(){return this;}});$.string=function(C,A,B){C=B.getElementById(C);
return(C)?$.element(C,A):null;};$.element=function(A,B){A.uid=A.uid||[Native.UID++];if(!B&&Garbage.collect(A)&&!A.$family){$extend(A,Element.Prototype);
}return A;};$.textnode=$.window=$.document=$arguments(0);$.number=function(A){return Garbage.Elements[A]||null;};Native.implement([Element,Document],{getElement:function(A,B){return $(this.getElements(A,true)[0]||null,B);
},getElements:function(A,D){A=A.split(",");var C=[];var B=(A.length>1);A.each(function(E){var F=this.getElementsByTagName(E.trim());(B)?C.extend(F):C=F;
},this);return new Elements(C,{ddup:B,cash:!D});}});Element.Storage={get:function(A){return(this[A]=this[A]||{});}};Element.Inserters=new Hash({before:function(B,A){if(A.parentNode){A.parentNode.insertBefore(B,A);
}},after:function(B,A){if(!A.parentNode){return ;}var C=A.nextSibling;(C)?A.parentNode.insertBefore(B,C):A.parentNode.appendChild(B);},bottom:function(B,A){A.appendChild(B);
},top:function(B,A){var C=A.firstChild;(C)?A.insertBefore(B,C):A.appendChild(B);}});Element.Inserters.inside=Element.Inserters.bottom;Element.Inserters.each(function(C,B){var A=B.capitalize();
Element.implement("inject"+A,function(D){Element.Inserters[B](this,$(D,true));return this;});Element.implement("grab"+A,function(D){Element.Inserters[B]($(D,true),this);
return this;});});Element.implement({getDocument:function(){return this.ownerDocument;},getWindow:function(){return this.ownerDocument.getWindow();},getElementById:function(D,C){var B=this.ownerDocument.getElementById(D);
if(!B){return null;}for(var A=B.parentNode;A!=this;A=A.parentNode){if(!A){return null;}}return $.element(B,C);},set:function(D,B){switch($type(D)){case"object":for(var C in D){this.set(C,D[C]);
}break;case"string":var A=Element.Properties.get(D);(A&&A.set)?A.set.apply(this,Array.slice(arguments,1)):this.setProperty(D,B);}return this;},get:function(B){var A=Element.Properties.get(B);
return(A&&A.get)?A.get.apply(this,Array.slice(arguments,1)):this.getProperty(B);},erase:function(B){var A=Element.Properties.get(B);(A&&A.erase)?A.erase.apply(this,Array.slice(arguments,1)):this.removeProperty(B);
return this;},match:function(A){return(!A||Element.get(this,"tag")==A);},inject:function(B,A){Element.Inserters.get(A||"bottom")(this,$(B,true));return this;
},wraps:function(B,A){B=$(B,true);return this.replaces(B).grab(B);},grab:function(B,A){Element.Inserters.get(A||"bottom")($(B,true),this);return this;},appendText:function(B,A){return this.grab(this.getDocument().newTextNode(B),A);
},adopt:function(){Array.flatten(arguments).each(function(A){this.appendChild($(A,true));},this);return this;},dispose:function(){return this.parentNode.removeChild(this);
},clone:function(B){var A=new Element("div").grab(this.cloneNode(B!==false));Array.each(A.getElementsByTagName("*"),function(C){if(C.id){C.removeAttribute("id");
}});return new Element("div").set("html",A.innerHTML).getFirst();},replaces:function(A){A=$(A,true);A.parentNode.replaceChild(this,A);return this;},hasClass:function(A){return this.className.contains(A," ");
},addClass:function(A){if(!this.hasClass(A)){this.className=(this.className+" "+A).clean();}return this;},removeClass:function(A){this.className=this.className.replace(new RegExp("(^|\\s)"+A+"(?:\\s|$)"),"$1").clean();
return this;},toggleClass:function(A){return this.hasClass(A)?this.removeClass(A):this.addClass(A);},getComputedStyle:function(C){var A=null;if(this.currentStyle){A=this.currentStyle[C.camelCase()];
}else{var B=this.getWindow().getComputedStyle(this,null);if(B){A=B.getPropertyValue([C.hyphenate()]);}}return A;},empty:function(){var A=$A(this.getElementsByTagName("*"));
A.each(function(B){$try(Element.prototype.dispose,B);});Garbage.trash(A);$try(Element.prototype.set,this,["html",""]);return this;},destroy:function(){Garbage.kill(this.empty().dispose());
return null;},toQueryString:function(){var A=[];this.getElements("input, select, textarea",true).each(function(D){var B=D.name,C=D.type,E=Element.get(D,"value");
if(E===false||!B||D.disabled){return ;}$splat(E).each(function(F){A.push(B+"="+encodeURIComponent(F));});});return A.join("&");},getProperty:function(C){var B=Element.Attributes,A=B.Props[C];
var D=(A)?this[A]:this.getAttribute(C);return(B.Bools[C])?!!D:D;},getProperties:function(){var A=$A(arguments);return A.map(function(B){return this.getProperty(B);
},this).associate(A);},setProperty:function(D,E){var C=Element.Attributes,B=C.Props[D],A=$defined(E);if(B&&C.Bools[D]){E=(E||!A)?true:false;}else{if(!A){return this.removeProperty(D);
}}(B)?this[B]=E:this.setAttribute(D,E);return this;},setProperties:function(A){for(var B in A){this.setProperty(B,A[B]);}return this;},removeProperty:function(D){var C=Element.Attributes,B=C.Props[D],A=(B&&C.Bools[D]);
(B)?this[B]=(A)?false:"":this.removeAttribute(D);return this;},removeProperties:function(){Array.each(arguments,this.removeProperty,this);return this;}});
(function(){var A=function(D,B,I,C,F,H){var E=D[I||B];var G=[];while(E){if(E.nodeType==1&&Element.match(E,C)){G.push(E);if(!F){break;}}E=E[B];}return(F)?new Elements(G,{ddup:false,cash:!H}):$(G[0],H);
};Element.implement({getPrevious:function(B,C){return A(this,"previousSibling",null,B,false,C);},getAllPrevious:function(B,C){return A(this,"previousSibling",null,B,true,C);
},getNext:function(B,C){return A(this,"nextSibling",null,B,false,C);},getAllNext:function(B,C){return A(this,"nextSibling",null,B,true,C);},getFirst:function(B,C){return A(this,"nextSibling","firstChild",B,false,C);
},getLast:function(B,C){return A(this,"previousSibling","lastChild",B,false,C);},getParent:function(B,C){return A(this,"parentNode",null,B,false,C);},getParents:function(B,C){return A(this,"parentNode",null,B,true,C);
},getChildren:function(B,C){return A(this,"nextSibling","firstChild",B,true,C);},hasChild:function(B){if(!(B=$(B,true))){return false;}return Element.getParents(B,this.get("tag"),true).contains(this);
}});})();Element.alias("dispose","remove").alias("getLast","getLastChild");Element.Properties=new Hash;Element.Properties.style={set:function(A){this.style.cssText=A;
},get:function(){return this.style.cssText;},erase:function(){this.style.cssText="";}};Element.Properties.value={get:function(){switch(Element.get(this,"tag")){case"select":var A=[];
Array.each(this.options,function(B){if(B.selected){A.push(B.value);}});return(this.multiple)?A:A[0];case"input":if(["checkbox","radio"].contains(this.type)&&!this.checked){return false;
}default:return $pick(this.value,false);}}};Element.Properties.tag={get:function(){return this.tagName.toLowerCase();}};Element.Properties.html={set:function(){return this.innerHTML=Array.flatten(arguments).join("");
}};Element.implement({getText:function(){return this.get("text");},setText:function(A){return this.set("text",A);},setHTML:function(){return this.set("html",arguments);
},getHTML:function(){return this.get("html");},getTag:function(){return this.get("tag");}});Native.implement([Element,Window,Document],{addListener:function(B,A){if(this.addEventListener){this.addEventListener(B,A,false);
}else{this.attachEvent("on"+B,A);}return this;},removeListener:function(B,A){if(this.removeEventListener){this.removeEventListener(B,A,false);}else{this.detachEvent("on"+B,A);
}return this;},retrieve:function(B,A){var D=Element.Storage.get(this.uid);var C=D[B];if($defined(A)&&!$defined(C)){C=D[B]=A;}return $pick(C);},store:function(B,A){var C=Element.Storage.get(this.uid);
C[B]=A;return this;},eliminate:function(A){var B=Element.Storage.get(this.uid);delete B[A];return this;}});Element.Attributes=new Hash({Props:{"html":"innerHTML","class":"className","for":"htmlFor","text":(Browser.Engine.trident)?"innerText":"textContent"},Bools:["compact","nowrap","ismap","declare","noshade","checked","disabled","readonly","multiple","selected","noresize","defer"],Camels:["value","accessKey","cellPadding","cellSpacing","colSpan","frameBorder","maxLength","readOnly","rowSpan","tabIndex","useMap"]});
(function(B){var C=B.Bools,A=B.Camels;B.Bools=C=C.associate(C);Hash.extend(Hash.merge(B.Props,C),A.associate(A.map(function(D){return D.toLowerCase();})));
B.remove("Camels");})(Element.Attributes);var Garbage={Elements:{},ignored:{object:1,embed:1,OBJECT:1,EMBED:1},collect:function(A){if(A.$attributes){return true;
}if(Garbage.ignored[A.tagName]){return false;}Garbage.Elements[A.uid]=A;A.$attributes={};return true;},trash:function(C){for(var A=C.length,B;A--;A){Garbage.kill(C[A]);
}},kill:function(A){if(!A||!A.$attributes){return ;}delete Garbage.Elements[A.uid];if(A.retrieve("events")){A.removeEvents();}for(var B in A.$attributes){A.$attributes[B]=null;
}if(Browser.Engine.trident){for(var C in Element.Prototype){A[C]=null;}}A.$attributes=A.uid=null;},empty:function(){for(var A in Garbage.Elements){Garbage.kill(Garbage.Elements[A]);
}}};window.addListener("beforeunload",function(){window.addListener("unload",Garbage.empty);if(Browser.Engine.trident){window.addListener("unload",CollectGarbage);
}});Element.Properties.events={set:function(A){this.addEvents(A);}};Native.implement([Element,Window,Document],{addEvent:function(E,G){var H=this.retrieve("events",{});
H[E]=H[E]||{"keys":[],"values":[]};if(H[E].keys.contains(G)){return this;}H[E].keys.push(G);var F=E,A=Element.Events.get(E),C=G,I=this;if(A){if(A.onAdd){A.onAdd.call(this,G);
}if(A.condition){C=function(J){if(A.condition.call(this,J)){return G.call(this,J);}return false;};}F=A.base||F;}var D=function(){return G.call(I);};var B=Element.NativeEvents[F]||0;
if(B){if(B==2){D=function(J){J=new Event(J,I.getWindow());if(C.call(I,J)===false){J.stop();}};}this.addListener(F,D);}H[E].values.push(D);return this;},removeEvent:function(D,C){var B=this.retrieve("events");
if(!B||!B[D]){return this;}var G=B[D].keys.indexOf(C);if(G==-1){return this;}var A=B[D].keys.splice(G,1)[0];var F=B[D].values.splice(G,1)[0];var E=Element.Events.get(D);
if(E){if(E.onRemove){E.onRemove.call(this,C);}D=E.base||D;}return(Element.NativeEvents[D])?this.removeListener(D,F):this;},addEvents:function(A){for(var B in A){this.addEvent(B,A[B]);
}return this;},removeEvents:function(B){var A=this.retrieve("events");if(!A){return this;}if(!B){for(var C in A){this.removeEvents(C);}A=null;}else{if(A[B]){while(A[B].keys[0]){this.removeEvent(B,A[B].keys[0]);
}A[B]=null;}}return this;},fireEvent:function(D,B,A){var C=this.retrieve("events");if(!C||!C[D]){return this;}C[D].keys.each(function(E){E.create({"bind":this,"delay":A,"arguments":B})();
},this);return this;},cloneEvents:function(D,A){D=$(D);var C=D.retrieve("events");if(!C){return this;}if(!A){for(var B in C){this.cloneEvents(D,B);}}else{if(C[A]){C[A].keys.each(function(E){this.addEvent(A,E);
},this);}}return this;}});Element.NativeEvents={"click":2,"dblclick":2,"mouseup":2,"mousedown":2,"contextmenu":2,"mousewheel":2,"DOMMouseScroll":2,"mouseover":2,"mouseout":2,"mousemove":2,"selectstart":2,"selectend":2,"keydown":2,"keypress":2,"keyup":2,"focus":2,"blur":2,"change":2,"reset":2,"select":2,"submit":2,"load":1,"unload":1,"beforeunload":1,"resize":1,"move":1,"DOMContentLoaded":1,"readystatechange":1,"error":1,"abort":1,"scroll":1};
(function(){var A=function(B){var C=B.relatedTarget;if(!C){return true;}return($type(this)!="document"&&C!=this&&C.prefix!="xul"&&!this.hasChild(C));};
Element.Events=new Hash({mouseenter:{base:"mouseover",condition:A},mouseleave:{base:"mouseout",condition:A},mousewheel:{base:(Browser.Engine.gecko)?"DOMMouseScroll":"mousewheel"}});
})();Element.Properties.styles={set:function(A){this.setStyles(A);}};Element.Properties.opacity={set:function(A,B){if(!B){if(A==0){if(this.style.visibility!="hidden"){this.style.visibility="hidden";
}}else{if(this.style.visibility!="visible"){this.style.visibility="visible";}}}if(!this.currentStyle||!this.currentStyle.hasLayout){this.style.zoom=1;}if(Browser.Engine.trident){this.style.filter=(A==1)?"":"alpha(opacity="+A*100+")";
}this.style.opacity=A;this.store("opacity",A);},get:function(){return this.retrieve("opacity",1);}};Element.implement({setOpacity:function(A){return this.set("opacity",A,true);
},getOpacity:function(){return this.get("opacity");},setStyle:function(B,A){switch(B){case"opacity":return this.set("opacity",parseFloat(A));case"float":B=(Browser.Engine.trident)?"styleFloat":"cssFloat";
}B=B.camelCase();if($type(A)!="string"){var C=(Element.Styles.get(B)||"@").split(" ");A=$splat(A).map(function(E,D){if(!C[D]){return"";}return($type(E)=="number")?C[D].replace("@",Math.round(E)):E;
}).join(" ");}else{if(A==String(Number(A))){A=Math.round(A);}}this.style[B]=A;return this;},getStyle:function(G){switch(G){case"opacity":return this.get("opacity");
case"float":G=(Browser.Engine.trident)?"styleFloat":"cssFloat";}G=G.camelCase();var A=this.style[G];if(!$chk(A)){A=[];for(var F in Element.ShortStyles){if(G!=F){continue;
}for(var E in Element.ShortStyles[F]){A.push(this.getStyle(E));}return A.join(" ");}A=this.getComputedStyle(G);}if(A){A=String(A);var C=A.match(/rgba?\([\d\s,]+\)/);
if(C){A=A.replace(C[0],C[0].rgbToHex());}}if(Browser.Engine.presto||(Browser.Engine.trident&&!$chk(parseInt(A)))){if(G.test(/^(height|width)$/)){var B=(G=="width")?["left","right"]:["top","bottom"],D=0;
B.each(function(H){D+=this.getStyle("border-"+H+"-width").toInt()+this.getStyle("padding-"+H).toInt();},this);return this["offset"+G.capitalize()]-D+"px";
}if(Browser.Engine.presto&&String(A).test("px")){return A;}if(G.test(/(border(.+)Width|margin|padding)/)){return"0px";}}return A;},setStyles:function(B){for(var A in B){this.setStyle(A,B[A]);
}return this;},getStyles:function(){var A={};Array.each(arguments,function(B){A[B]=this.getStyle(B);},this);return A;}});Element.Styles=new Hash({width:"@px",height:"@px",left:"@px",top:"@px",bottom:"@px",right:"@px",maxWidth:"@px",maxHeight:"@px",backgroundColor:"rgb(@, @, @)",backgroundPosition:"@px @px",color:"rgb(@, @, @)",fontSize:"@px",letterSpacing:"@px",lineHeight:"@px",clip:"rect(@px @px @px @px)",margin:"@px @px @px @px",padding:"@px @px @px @px",border:"@px @ rgb(@, @, @) @px @ rgb(@, @, @) @px @ rgb(@, @, @)",borderWidth:"@px @px @px @px",borderStyle:"@ @ @ @",borderColor:"rgb(@, @, @) rgb(@, @, @) rgb(@, @, @) rgb(@, @, @)",zIndex:"@","zoom":"@",fontWeight:"@",textIndent:"@px",opacity:"@"});
Element.ShortStyles={"margin":{},"padding":{},"border":{},"borderWidth":{},"borderStyle":{},"borderColor":{}};["Top","Right","Bottom","Left"].each(function(G){var F=Element.ShortStyles;
var B=Element.Styles;["margin","padding"].each(function(H){var I=H+G;F[H][I]=B[I]="@px";});var E="border"+G;F.border[E]=B[E]="@px @ rgb(@, @, @)";var D=E+"Width",A=E+"Style",C=E+"Color";
F[E]={};F.borderWidth[D]=F[E][D]=B[D]="@px";F.borderStyle[A]=F[E][A]=B[A]="@";F.borderColor[C]=F[E][C]=B[C]="rgb(@, @, @)";});(function(){function A(B){return B.tagName.toLowerCase()=="body";
}Element.implement({positioned:function(){if(A(this)){return true;}return(Element.getComputedStyle(this,"position")!="static");},getOffsetParent:function(){if(A(this)){return null;
}if(!Browser.Engine.trident){return $(this.offsetParent);}var B=this;while((B=B.parentNode)){if(Element.positioned(B)){return $(B);}}return null;},getSize:function(){if(A(this)){return this.getWindow().getSize();
}return{x:this.offsetWidth,y:this.offsetHeight};},getScrollSize:function(){if(A(this)){return this.getWindow().getScrollSize();}return{x:this.scrollWidth,y:this.scrollHeight};
},getScroll:function(){if(A(this)){return this.getWindow().getScroll();}return{x:this.scrollLeft,y:this.scrollTop};},scrollTo:function(B,C){if(A(this)){return this.getWindow().scrollTo(B,C);
}this.scrollLeft=B;this.scrollTop=C;return this;},getPosition:function(D){if(A(this)){return{x:0,y:0};}var C=this,B={x:0,y:0};while(C){B.x+=C.offsetLeft;
B.y+=C.offsetTop;C=C.offsetParent;}var E=(D)?$(D).getPosition():{x:0,y:0};return{x:B.x-E.x,y:B.y-E.y};},getCoordinates:function(D){if(A(this)){return this.getWindow().getCoordinates();
}var B=this.getPosition(D),C=this.getSize();var E={"top":B.y,"left":B.x,"width":C.x,"height":C.y};E.right=E.left+E.width;E.bottom=E.top+E.height;return E;
},getRelativePosition:function(){return this.getPosition(this.getOffsetParent());},computePosition:function(B){return{left:B.x-(this.getComputedStyle("margin-left").toInt()||0),top:B.y-(this.getComputedStyle("margin-top").toInt()||0)};
},position:function(B){return this.setStyles(this.computePosition(B));}});})();Native.implement([Window,Document],{getSize:function(){var A=this.getDocument().body,B=this.getDocument().documentElement;
if(Browser.Engine.webkit419){return{x:this.innerWidth,y:this.innerHeight};}return{x:B.clientWidth,y:B.clientHeight};},getScroll:function(){var A=this.getDocument().documentElement;
return{x:$pick(this.pageXOffset,A.scrollLeft),y:$pick(this.pageYOffset,A.scrollTop)};},getScrollSize:function(){var B=this.getDocument().documentElement,A=this.getDocument().body;
if(Browser.Engine.trident){return{x:Math.max(B.clientWidth,B.scrollWidth),y:Math.max(B.clientHeight,B.scrollHeight)};}if(Browser.Engine.webkit){return{x:A.scrollWidth,y:A.scrollHeight};
}return{x:B.scrollWidth,y:B.scrollHeight};},getPosition:function(){return{x:0,y:0};},getCoordinates:function(){var A=this.getSize();return{top:0,left:0,height:A.y,width:A.x,bottom:A.y,right:A.x};
}});Native.implement([Window,Document,Element],{getHeight:function(){return this.getSize().y;},getWidth:function(){return this.getSize().x;},getScrollTop:function(){return this.getScroll().y;
},getScrollLeft:function(){return this.getScroll().x;},getScrollHeight:function(){return this.getScrollSize().y;},getScrollWidth:function(){return this.getScrollSize().x;
},getTop:function(){return this.getPosition().y;},getLeft:function(){return this.getPosition().x;}});Native.implement([Element,Document],{getElements:function(N,M){var J={};
N=N.split(",");var A=[],H=N.length;var B=(H>1);for(var I=0;I<H;I++){var E=N[I],K=[],G=[];E=E.trim().replace(Selectors.sRegExp,function(P){if(P.charAt(2)){P=P.trim();
}G.push(P.charAt(0));return":)"+P.charAt(1);}).split(":)");for(var F=0,D=E.length;F<D;F++){var C=Selectors.parse(E[F]);if(!C){return[];}var O=Selectors.Method.getParam(K,G[F-1]||false,this,C,J);
if(!O){break;}K=O;}var L=Selectors.Method.getItems(K,this);A=(B)?A.concat(L):L;}return new Elements(A,{ddup:B,cash:!M});}});Window.implement({$E:function(A){return this.document.getElement(A);
}});var Selectors={regExp:(/:([^-:(]+)[^:(]*(?:\((["']?)(.*?)\2\))?|\[(\w+)(?:([!*^$~|]?=)(["']?)(.*?)\6)?\]|\.[\w-]+|#[\w-]+|\w+|\*/g),sRegExp:(/\s*([+>~\s])[a-zA-Z#.*\s]/g)};
Selectors.parse=function(A){var B={tag:"*",id:null,classes:[],attributes:[],pseudos:[]};A=A.replace(Selectors.regExp,function(E){switch(E.charAt(0)){case".":B.classes.push(E.slice(1));
break;case"#":B.id=E.slice(1);break;case"[":B.attributes.push([arguments[4],arguments[5],arguments[7]]);break;case":":var D=Selectors.Pseudo.get(arguments[1]);
if(!D){B.attributes.push([arguments[1],arguments[3]?"=":"",arguments[3]]);break;}var C={"name":arguments[1],"parser":D,"argument":(D.parser)?D.parser(arguments[3]):arguments[3]};
B.pseudos.push(C);break;default:B.tag=E;}return"";});return B;};Selectors.Pseudo=new Hash;Selectors.XPath={getParam:function(B,G,D,H){var A="";switch(G){case" ":A+="//";
break;case">":A+="/";break;case"+":A+="/following-sibling::*[1]/self::";break;case"~":A+="/following-sibling::";break;}A+=(D.namespaceURI)?"xhtml:"+H.tag:H.tag;
var C;for(C=H.pseudos.length;C--;C){var F=H.pseudos[C];if(F.parser&&F.parser.xpath){A+=F.parser.xpath(F.argument);}else{A+=($chk(F.argument))?"[@"+F.name+'="'+F.argument+'"]':"[@"+F.name+"]";
}}if(H.id){A+='[@id="'+H.id+'"]';}for(C=H.classes.length;C--;C){A+='[contains(concat(" ", @class, " "), " '+H.classes[C]+' ")]';}for(C=H.attributes.length;
C--;C){var E=H.attributes[C];switch(E[1]){case"=":A+="[@"+E[0]+'="'+E[2]+'"]';break;case"*=":A+="[contains(@"+E[0]+', "'+E[2]+'")]';break;case"^=":A+="[starts-with(@"+E[0]+', "'+E[2]+'")]';
break;case"$=":A+="[substring(@"+E[0]+", string-length(@"+E[0]+") - "+E[2].length+' + 1) = "'+E[2]+'"]';break;case"!=":A+="[@"+E[0]+'!="'+E[2]+'"]';break;
case"~=":A+='[contains(concat(" ", @'+E[0]+', " "), " '+E[2]+' ")]';break;case"|=":A+='[contains(concat("-", @'+E[0]+', "-"), "-'+E[2]+'-")]';break;default:A+="[@"+E[0]+"]";
}}B.push(A);return B;},getItems:function(B,E){var F=[];var G=E.getDocument();var A=G.evaluate(".//"+B.join(""),E,Selectors.XPath.resolver,XPathResult.UNORDERED_NODE_SNAPSHOT_TYPE,null);
for(var D=0,C=A.snapshotLength;D<C;D++){F[D]=A.snapshotItem(D);}return F;},resolver:function(A){return(A=="xhtml")?"http://www.w3.org/1999/xhtml":false;
}};Selectors.Filter={getParam:function(H,B,A,P,Q){var F=[];var R=P.tag;if(B){var C={},E,D,O,L,K;var G=function(S){S.uid=S.uid||[Native.UID++];if(!C[S.uid]&&Selectors.Filter.match(S,P,Q)){C[S.uid]=true;
F.push(S);return true;}return false;};for(var N=0,M=H.length;N<M;N++){O=H[N];switch(B){case" ":D=O.getElementsByTagName(R);P.tag=false;for(L=0,K=D.length;
L<K;L++){G(D[L]);}break;case">":D=O.childNodes;for(L=0,K=D.length;L<K;L++){if(D[L].nodeType==1){G(D[L]);}}break;case"+":while((O=O.nextSibling)){if(O.nodeType==1){G(O);
break;}}break;case"~":while((O=O.nextSibling)){if(O.nodeType==1&&G(O)){break;}}break;}}return F;}if(P.id){el=A.getElementById(P.id,true);P.id=false;return(el&&Selectors.Filter.match(el,P,Q))?[el]:false;
}else{H=A.getElementsByTagName(R);P.tag=false;for(var J=0,I=H.length;J<I;J++){if(Selectors.Filter.match(H[J],P,Q)){F.push(H[J]);}}}return F;},getItems:$arguments(0)};
Selectors.Filter.match=function(C,E,G){G=G||{};if(E.id&&E.id!=C.id){return false;}if(E.tag&&E.tag!="*"&&E.tag!=C.tagName.toLowerCase()){return false;}var B;
for(B=E.classes.length;B--;B){if(!C.className||!C.className.contains(E.classes[B]," ")){return false;}}for(B=E.attributes.length;B--;B){var D=E.attributes[B];
var A=Element.prototype.getProperty.call(C,D[0]);if(!A){return false;}if(!D[1]){continue;}var F;switch(D[1]){case"=":F=(A==D[2]);break;case"*=":F=(A.contains(D[2]));
break;case"^=":F=(A.substr(0,D[2].length)==D[2]);break;case"$=":F=(A.substr(A.length-D[2].length)==D[2]);break;case"!=":F=(A!=D[2]);break;case"~=":F=A.contains(D[2]," ");
break;case"|=":F=A.contains(D[2],"-");}if(!F){return false;}}for(B=E.pseudos.length;B--;B){if(!E.pseudos[B].parser.filter.call(C,E.pseudos[B].argument,G)){return false;
}}return true;};Selectors.Method=(Browser.Features.xpath)?Selectors.XPath:Selectors.Filter;Element.implement({match:function(A){return(!A||Selectors.Filter.match(this,Selectors.parse(A)));
}});